name: Train and Test Iris Classifier (All rows)

on:
  push:
    branches:
      - main
    paths:
      - 'iris_classifier.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Train and Test
      run: python iris_classifier.py
